[package]
name = "variables"
version = "2.3.4"
authors = ["Ana LÃ­rio <afrolirio@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
